name: Auto-Smash Proxies 

on:
 schedule:
   - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch: # Allows you to run it manually with a button click 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
     contents: write # Allows the bot to push changes back to your repo
    steps: 
     - name: Checkout Repo
       uses: actions/checkout@v4 
       
     - name: Make Script Executable
        run: chmod +x smash.sh 
        
     - name: Run Smash Script 
       run: ./smash.sh 
       
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add happ_config.txt
          git commit -m "🔄 Auto-update: $(date)" || 
          git push
